export const experiences = [
  {
    id: '1',
    company: 'TECHSPACE COMPANY LIMITED',
    role: 'Software Developer',
    type: 'Full-time',
    period: 'Nov 4, 2025 – Feb 27, 2026',
    duration: '~4 months',
    description:
      'Continuing as a full-time Software Developer after internship. Focused on building the Custom Report — Report Generator system, writing requirement specs, designing ER diagrams, and developing ERP features with Laravel (PHP) and MySQL.',
    tech: ['Laravel', 'PHP', 'MySQL', 'BitBucket', 'ER Diagram'],
    color: 'rgba(6,182,212)',
    bgColor: 'rgba(6,182,212,0.05)',
    borderColor: 'rgba(6,182,212,0.4)',
  },
  {
    id: '2',
    company: 'TECHSPACE COMPANY LIMITED',
    role: 'Software Developer Intern',
    type: 'Internship',
    period: 'Jun 4, 2025 – Sep 19, 2025',
    duration: '3 months',
    description:
      'Focused on Custom Off-page development with a Code Editor project — built a code editor tool integrated into the ERP system for page customization. Used Laravel (PHP), jQuery, and WebSocket for backend and frontend. Collected requirements from users and translated them into system features. Designed ERP editor interface using Figma.',
    tech: ['Laravel', 'PHP', 'jQuery', 'WebSocket', 'Figma', 'MySQL'],
    color: 'rgba(34,197,94)',
    bgColor: 'rgba(34,197,94,0.05)',
    borderColor: 'rgba(34,197,94,0.4)',
  },
  {
    id: '3',
    company: 'MAMMOSSIX ASIA CO., LTD.',
    role: 'Game Programmer Intern',
    type: 'Internship',
    period: 'Nov 25, 2024 – Apr 30, 2025',
    duration: '5 months',
    description:
      'Developed a 2D mobile game in Unity as part of an internship project. Implemented gameplay mechanics, user interface, Leaderboard, and core functionality. Published on mobile and Android platforms. Used Firebase for backend and GitLab for version control.',
    tech: ['Unity', 'C#', 'Firebase', 'GitLab', 'Android', 'iOS'],
    color: 'rgba(249,115,22)',
    bgColor: 'rgba(249,115,22,0.05)',
    borderColor: 'rgba(249,115,22,0.4)',
  },
];

export const education = [
  {
    id: '1',
    school: 'University of Phayao',
    degree: 'Bachelor of Engineering – Software Engineering',
    period: 'May 2022 – Present',
    gpa: '3.55',
    note: 'Phayao, Thailand',
    subjects: [
      'UXUI',
      'OOP',
      'Data Structure',
      'Software Requirements',
      'Front-End',
      'Back-End',
      'Database System',
      'Software Process',
      'Software Testing',
      'Project Management (Agile)',
    ],
  },
  {
    id: '2',
    school: 'Wittayanukul Naree School',
    degree: 'Mathematics & Science',
    period: 'May 2019 – Feb 2022',
    gpa: '3.17',
    note: 'High School · Phetchabun, Thailand',
    subjects: [],
  },
];
