// Add new projects here — just push a new object to the array!
// For screenshots: place images in /public/ and reference as '/filename.png'
// or use external URLs.

export const projects = [
  {
    id: '1',
    screenshot: 'https://raw.githubusercontent.com/dewakuneiei/code-collector/main/images/code_collector_dark.png',
    title: 'Code Collector',
    subTitle: 'High-performance desktop code extraction tool',
    stack: ['Rust', 'Desktop GUI', 'CLI', 'Cross-platform'],
    description:
      'A high-performance desktop GUI tool designed to help developers extract, filter, and export code from their projects. Perfect for preparing context for LLMs (ChatGPT, Claude, DeepSeek), creating backups, or reviewing large codebases.',
    date: '2025',
    github: 'https://github.com/dewakuneiei/code-collector',
    live: 'https://github.com/dewakuneiei/code-collector',
    liveLabel: 'View on GitHub',
    color: 'rgba(239,68,68)',
    btnBg: 'rgba(153,27,27,0.5)',
    btnBgHover: 'rgba(69,10,10)',
    cardBg: 'rgba(153,27,27,0.05)',
    current: false,
  },
  {
    id: '2',
    screenshot: '/projects/lacoupong.jpg',
    title: 'Lacoupong',
    subTitle: 'Collaborative web application',
    stack: ['Next.js', 'TypeScript', 'Tailwind CSS', 'Team Project'],
    description:
      'A collaborative team web application project. Contributed to frontend development, UI design, and integration with backend APIs. Live at lacoupong.vercel.app.',
    date: '2025',
    github: 'https://github.com/paihaisuth/lacupong.web.fn',
    live: 'https://lacoupong.vercel.app/',
    liveLabel: 'Live Demo',
    color: 'rgba(34,197,94)',
    btnBg: 'rgba(22,101,52,0.5)',
    btnBgHover: 'rgba(5,46,22)',
    cardBg: 'rgba(22,101,52,0.05)',
    current: false,
  },
  {
    id: '3',
    screenshot: '/projects/next_game_overview.jpg',
    title: 'Next.js Game',
    subTitle: '5-in-1 mini game collection',
    stack: ['Next.js', 'TypeScript', 'Tailwind CSS', 'Framer Motion'],
    description:
      'A web-based mini game collection featuring 5 different games, built with Next.js, TypeScript, Tailwind CSS, and Framer Motion. Demonstrates modern full-stack web development with interactive animations.',
    date: 'May 2025',
    github: 'https://github.com/dewakuneiei/nextjs-games',
    live: 'https://nextjs-games-nine.vercel.app/',
    liveLabel: 'Play Now',
    color: 'rgba(99,102,241)',
    btnBg: 'rgba(55,48,163,0.5)',
    btnBgHover: 'rgba(30,27,75)',
    cardBg: 'rgba(55,48,163,0.05)',
    current: false,
  },
  {
    id: '4',
    screenshot: '/projects/UPPOP_Logo.jpg',
    title: 'UP POP App',
    subTitle: 'University of Phayao — Figma Design',
    stack: ['Figma', 'UI/UX', 'Prototype', 'Mobile Design'],
    description:
      'A mobile application UI/UX design project for University of Phayao (UP POP). Created a full interactive prototype in Figma, demonstrating design skills including user flow, wireframing, and high-fidelity mockups.',
    date: '2024',
    github: '',
    live: 'https://www.figma.com/proto/HaobbpyJ5PaYuDjIHKLzvG/App--UP-POP?node-id=160-192&p=f&t=QZOw9Z4poIkVH6Dl-1&scaling=scale-down&content-scaling=fixed&page-id=0%3A1&starting-point-node-id=540%3A4330',
    liveLabel: 'View Prototype',
    color: 'rgba(6,182,212)',
    btnBg: 'rgba(7,89,133,0.5)',
    btnBgHover: 'rgba(8,47,73)',
    cardBg: 'rgba(7,89,133,0.05)',
    current: false,
  },
  {
    id: '5',
    screenshot: '/projects/roblox_academy_prototype_version.png',
    title: 'Game Dev Academy',
    subTitle: 'Duolingo-inspired game development learning platform',
    stack: ['Next.js', 'TypeScript', 'Tailwind CSS', 'Web App'],
    description:
      'A web application inspired by Duolingo — designed to teach game development concepts through interactive lessons, quizzes, and challenges. Making game dev education accessible and engaging for beginners. (Prototype built with Next.js, Tailwind CSS, and Framer Motion.)',
    date: '2026',
    github: '',
    live: 'https://roblox-academy-rpg-prototyping.vercel.app/',
    liveLabel: 'View Prototype',
    color: 'rgba(251,191,36)',
    btnBg: 'rgba(146,64,14,0.5)',
    btnBgHover: 'rgba(67,20,7)',
    cardBg: 'rgba(146,64,14,0.05)',
    current: true,
  },
  {
    id: '6',
    screenshot: 'https://tr.rbxcdn.com/180DAY-4084e7d0e83406fb5fdecca9e97af508/768/432/Image/Webp/noFilter',
    title: 'Namtar 2',
    subTitle: 'Thai Shooting Horror Game — Roblox',
    stack: ['Roblox Studio', 'Lua', 'Game Design', 'Horror'],
    description:
      'A Thai shooting horror game on Roblox — players fight through terrifying environments inspired by Thai ghost folklore. The sequel to Namtar, which was the original Thai ghost traditional RPG. Still in active development with new mechanics and story content being added.',
    date: '2026',
    github: '',
    live: 'https://www.roblox.com/games/130014192684011/Namtar-2',
    liveLabel: 'Play on Roblox',
    color: 'rgba(249,115,22)',
    btnBg: 'rgba(154,52,18,0.5)',
    btnBgHover: 'rgba(67,20,7)',
    cardBg: 'rgba(154,52,18,0.05)',
    current: true,
    prevVideo: 'https://youtu.be/kZVl8ztk-jw?si=YcRZdbZn5LqTq0vF',
    prevVideoLabel: 'Watch Namtar 1 Preview',
  },
];
