// Add new projects here — just push a new object to the array!
// For screenshots: place images in /public/ and reference as '/filename.png'
// or use external URLs.

export const projects = [
  {
    id: '1',
    screenshot: 'https://img.youtube.com/vi/kZVl8ztk-jw/maxresdefault.jpg',
    title: 'Namtar',
    subTitle: 'Thai Ghost Traditional — Roblox Game',
    stack: ['Roblox Studio', 'Lua', 'Game Design', 'Multiplayer'],
    description:
      'A Roblox multiplayer game inspired by Thai ghost folklore (ผีไทย). Players explore and interact with traditional Thai ghost stories in an immersive game world built with Roblox Studio and Lua scripting.',
    date: '2025',
    github: '',
    live: 'https://youtu.be/kZVl8ztk-jw?si=-41RRL8FjyUdXDTR',
    liveLabel: 'Watch on YouTube',
    color: 'rgba(249,115,22)',
    btnBg: 'rgba(154,52,18,0.5)',
    btnBgHover: 'rgba(67,20,7)',
    cardBg: 'rgba(154,52,18,0.05)',
  },
  {
    id: '2',
    screenshot: 'https://opengraph.githubassets.com/1/dewakuneiei/code-collector',
    title: 'Code Collector',
    subTitle: 'High-performance desktop code extraction tool',
    stack: ['Rust', 'Desktop GUI', 'CLI', 'Cross-platform'],
    description:
      'A high-performance desktop GUI tool designed to help developers extract, filter, and export code from their projects. Perfect for preparing context for LLMs (ChatGPT, Claude, DeepSeek), creating backups, or reviewing large codebases.',
    date: '2025',
    github: 'https://github.com/dewakuneiei/code-collector',
    live: 'https://github.com/dewakuneiei/code-collector',
    liveLabel: 'View on GitHub',
    color: 'rgba(239,68,68)',
    btnBg: 'rgba(153,27,27,0.5)',
    btnBgHover: 'rgba(69,10,10)',
    cardBg: 'rgba(153,27,27,0.05)',
  },
  {
    id: '3',
    screenshot: 'https://opengraph.githubassets.com/1/dewakuneiei/loan-game',
    title: 'Loan Game',
    subTitle: '5-in-1 mini game collection',
    stack: ['Next.js', 'TypeScript', 'Tailwind CSS', 'Framer Motion'],
    description:
      'A web-based mini game collection featuring 5 different games, built with Next.js, TypeScript, Tailwind CSS, and Framer Motion. Demonstrates modern full-stack web development with interactive animations.',
    date: '2025',
    github: 'https://github.com/dewakuneiei/loan-game',
    live: 'https://github.com/dewakuneiei/loan-game',
    liveLabel: 'View on GitHub',
    color: 'rgba(99,102,241)',
    btnBg: 'rgba(55,48,163,0.5)',
    btnBgHover: 'rgba(30,27,75)',
    cardBg: 'rgba(55,48,163,0.05)',
  },
  {
    id: '4',
    screenshot: 'https://opengraph.githubassets.com/1/paihaisuth/lacupong.web.fn',
    title: 'Lacoupong',
    subTitle: 'Collaborative web application',
    stack: ['Next.js', 'TypeScript', 'Tailwind CSS', 'Team Project'],
    description:
      'A collaborative team web application project. Contributed to frontend development, UI design, and integration with backend APIs. Live at lacoupong.vercel.app.',
    date: '2025',
    github: 'https://github.com/paihaisuth/lacupong.web.fn',
    live: 'https://lacoupong.vercel.app/',
    liveLabel: 'Live Demo',
    color: 'rgba(34,197,94)',
    btnBg: 'rgba(22,101,52,0.5)',
    btnBgHover: 'rgba(5,46,22)',
    cardBg: 'rgba(22,101,52,0.05)',
  },
  {
    id: '5',
    screenshot: 'https://roblox-academy-rpg-prototyping.vercel.app/api/og',
    title: 'Roblox Academy RPG',
    subTitle: 'RPG game prototype web app',
    stack: ['Next.js', 'TypeScript', 'Tailwind CSS', 'Framer Motion'],
    description:
      'A web-based prototype for an RPG-style Roblox Academy experience. Demonstrates UI design, interactive game elements, and modern Next.js development.',
    date: '2025',
    github: '',
    live: 'https://roblox-academy-rpg-prototyping.vercel.app/',
    liveLabel: 'Live Prototype',
    color: 'rgba(139,92,246)',
    btnBg: 'rgba(91,33,182,0.5)',
    btnBgHover: 'rgba(46,16,101)',
    cardBg: 'rgba(91,33,182,0.05)',
  },
  {
    id: '6',
    screenshot: 'https://placehold.co/350x400/1a1a2e/38bdf8?text=College+App',
    title: 'UP POP App',
    subTitle: 'University of Phayao — Figma Design',
    stack: ['Figma', 'UI/UX', 'Prototype', 'Mobile Design'],
    description:
      'A mobile application UI/UX design project for University of Phayao (UP POP). Created a full interactive prototype in Figma, demonstrating design skills including user flow, wireframing, and high-fidelity mockups.',
    date: '2024',
    github: '',
    live: 'https://www.figma.com/proto/HaobbpyJ5PaYuDjIHKLzvG/App--UP-POP?node-id=160-192&p=f&t=QZOw9Z4poIkVH6Dl-1&scaling=scale-down&content-scaling=fixed&page-id=0%3A1&starting-point-node-id=540%3A4330',
    liveLabel: 'View Prototype',
    color: 'rgba(6,182,212)',
    btnBg: 'rgba(7,89,133,0.5)',
    btnBgHover: 'rgba(8,47,73)',
    cardBg: 'rgba(7,89,133,0.05)',
  },
];
